server:
  port: 8081

com:
  ex:
    uploadPath: /SpringBoot_Project/src/main/resources/static/tmpImg/

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: teamproject

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://testdb2.cjy0cyq66hv0.us-east-1.rds.amazonaws.com:3306/testdb2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: tmdhkzh77!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    remember-me:
      key: dsijeirkji348ewjid!@Fji@#
      tokenValiditySeconds: 3600

  mail:
    host: smtp.gmail.com
    port: 587
    username: ???
    password: ????
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true